### ISSUE TITLE
Documentation has wrong example

### ISSUE THREAD

**Issue by dewey** [bharget/heroicon#27]
Hey, just noticed that the README has some outdated examples. It's referring to `<%= heroicon "search" %>` but that one doesn't exist any more, it's now called `magnifying-glass` from what I can tell.

Just took me a moment to realize why my test didn't work 😬

**Comment by ZilvinasKucinskas** [comment]
https://github.com/bharget/heroicon/pull/24 resolves this issue.

**Comment by bharget** [comment]
This is fixed 😄
