### ISSUE TITLE
uninitialized constant Heroicon

### ISSUE THREAD

**Issue by 7200rpm** [bharget/heroicon#6]
I've added this gem to my rails project following the installation instructions. However, I'm getting an error on starting my rails server:

```
config/initializers/heroicon.rb:3:in `<main>': uninitialized constant Heroicon (NameError)
```
Do I need to add something else to my code?

**Comment by bharget** [comment]
Hi @7200rpm ! Any chance that you need to `bundle install` and restart your server? Let me know if this works and I'll look into it if not!

**Comment by TanZng** [comment]
Reload the server worked for me, thanks! I think it's because configs are read-only when the server it's start :D
