### ISSUE TITLE
Lack of default sizes

### ISSUE THREAD

**Issue by mzrnsh** [bharget/heroicon#8]
When you copy an icon from [heroicons.com](https://heroicons.com), both the SVG and the JSX versions come with `.h-6` & `.w-6` classes for medium icons and `.h-5` & `.w-5` classes for small icons.

When using TailwindCSS, this produces correct icon sizes most of the times. Well, at least from my experience it does. So when I go with the copy&paste approach, in most cases I don't have to provide extra classes or styles, it just works.

But it seems to me that with Heroicon, I will need to provide these classes manually all the time. Right now, my typical usage of Heroicon looks like this:
```erb
<%= heroicon 'chevron-right', options: { class: "h-5 w-5" } %>
```
But I'd really love to be able to use this 9 out of 10 times instead:
```erb
<%= heroicon 'chevron-right' %>
```
In other words, would be great if we have to provide options only for non-standard use cases, like custom sizes, positioning classes etc, otherwise we use the bare helper.

This could be configurable to allow overriding the defaults. For example, like this:

```ruby
Heroicon.configure do |config|
  config.variant = :solid
  config.classes = { outline: 'h-6 w-6', solid: 'h-5 w-5' }
end
```

I'd  argue that these values should come as default. I understand that not everyone is using TailwindCSS, but if you copy the icons from the official site, you are getting those classes anyway. So if this gem is about replacing the copy&paste step in your workflow while leaving everything else unchanged, then these defaults make sense.

What do you guys think?

Maybe I missed something and it is already possible achieve this?

**Comment by bharget** [comment]
I totally agree that this could be a useful feature, and a similar thought has crossed my mind! I will say, I'm not sure I totally see the value in having separate defaults for solid/outline. Is this something that your application needs in particular? Or are you just looking for default class names in general?

For example, see #10 for how this could work with a single option.
